name: Pylint

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install --upgrade --pre pylint-odoo
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=8.5 --rcfile=$(git ls-files '.pylintrc') $(git ls-files 'modules/')
