# -*- coding: utf-8 -*-
{

    'name': 'Theme Laze',
    'category': 'Theme/Ecommerce',
    'summary': """Multipurpose Premium Responsive Odoo Theme - Fashion, Furniture, Sports, Jewellery, Corporate
    Creative theme,
Ecommerce theme,
Entertainment theme,
Personal theme,
Services theme,
Technology theme,
Business theme,
Multipurpose odoo theme,
Multi-purpose theme,
Theme Laze,
Odoo new themes,
Laze Theme,
Bootstrap4 odoo themes,
eCommerce Businesses,
    """,
    'version': '1.4',
    'sequence': 1000,
    'author': 'Atharva System',
    'license' : 'OPL-1',
    'support': 'support@atharvasystem.com',
    'website' : 'https://www.atharvasystem.com',
    'description': """
    Theme Laze is one of the most powerful, amazing and flexible theme on Odoo store.
    Multipurpose Premium Responsive Odoo Themes - Fashion, Furniture, Sports, Jewellery, Corporate.
        """,
    'depends': [
        'atharva_theme_base'
    ],
    'data':[
        'data/slider_layout_data.xml',
        'data/varient_slider_layout_data.xml',
        'data/common_slider_layout_data.xml',
        'data/brand_slider_layout_data.xml',
        'data/category_slider_layout_data.xml',
        'views/assets.xml',
        'views/product_quick_view_template.xml',
        'views/brand_page_template.xml',
        'views/product_rating.xml',
        'views/product_label_template.xml',
        'views/snippets/s_laze_snippet_builder.xml',
        'views/snippets/s_product_slider.xml',
        'views/snippets/s_product_var_slider.xml',
        'views/snippets/s_brand_slider.xml',
        'views/snippets/s_category_slider.xml',
        'views/snippets/s_blog_slider.xml',
        'views/snippets/snippets.xml',
        'views/snippets/snippet_header.xml',
        'views/snippets/s_faqs_snippet.xml',
        'views/snippets/snippet_footer.xml',
        'views/product_slider_template.xml',
        'views/varient_product_slider_template.xml',
        'views/common_slider_layout_template.xml',
        'views/brand_slider_layout_template.xml',
        'views/category_slider_layout_template.xml',
        'views/product_share.xml',
        'views/custom_header.xml',
        'views/custom_footer.xml',
        'views/product_detail_template.xml',
        'views/shop.xml',
        'views/custom_button.xml',
        'views/snippets/snippet_button.xml',
        'views/multi_image_slider.xml',
    ],
    'live_test_url': 'https://laze-v14.atharvasystem.com/',
    'images': ['static/description/laze_banner.png','static/description/laze_banner_screenshot.png'],
    'price': 75.00,
    'currency': 'EUR',
    'application': False,
}
